[菜鸟教程-numpy](https://www.runoob.com/numpy/numpy-tutorial.html)

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'  #默认为'last'
%matplotlib inline

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time
import os
import sys
import random
from numpy import linalg
np.set_printoptions(threshold=np.inf, precision=2, suppress=True)

# 基本

# 线性代数

##### 创建矩阵

In [4]:
# a = np.array([])
np.random.seed(2020)
A = np.random.randint(0, 10, size=(3, 3))
A

array([[0, 8, 3],
       [6, 3, 3],
       [7, 8, 0]])

## 行列式
* det()

In [83]:
A = np.array([3,-2,2,1]).reshape(2,2)
linalg.det(A)

6.999999999999999

## 逆矩阵  
* inv()

In [6]:
A_1 = linalg.inv(A)
A_1
A@A_1
A_1@A

array([[-0.1 ,  0.1 ,  0.06],
       [ 0.08, -0.08,  0.07],
       [ 0.11,  0.22, -0.19]])

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0.,  0.,  1.]])

## 广义逆矩阵
* pinv()

In [82]:
A = np.mat("4 11 14;8 7 -2")
# 使用pinv函数计算广义逆矩阵
pseudoinv = linalg.pinv(A)
pseudoinv
A.shape
pseudoinv.shape
A@pseudoinv
pseudoinv@A

matrix([[-0.01,  0.07],
        [ 0.02,  0.04],
        [ 0.06, -0.06]])

(2, 3)

(3, 2)

matrix([[1., 0.],
        [0., 1.]])

matrix([[ 0.56,  0.44, -0.22],
        [ 0.44,  0.56,  0.22],
        [-0.22,  0.22,  0.89]])

In [74]:
help(linalg.pinv)

Help on function pinv in module numpy.linalg:

pinv(a, rcond=1e-15)
    Compute the (Moore-Penrose) pseudo-inverse of a matrix.
    
    Calculate the generalized inverse of a matrix using its
    singular-value decomposition (SVD) and including all
    *large* singular values.
    
    .. versionchanged:: 1.14
       Can now operate on stacks of matrices
    
    Parameters
    ----------
    a : (..., M, N) array_like
        Matrix or stack of matrices to be pseudo-inverted.
    rcond : (...) array_like of float
        Cutoff for small singular values.
        Singular values smaller (in modulus) than
        `rcond` * largest_singular_value (again, in modulus)
        are set to zero. Broadcasts against the stack of matrices
    
    Returns
    -------
    B : (..., N, M) ndarray
        The pseudo-inverse of `a`. If `a` is a `matrix` instance, then so
        is `B`.
    
    Raises
    ------
    LinAlgError
        If the SVD computation does not converge.
    
    Notes
    -

## 解线性方程

* solve()

In [8]:
B = np.array([1, -2, 1, 0, 2, -8, -4, 5, 9]).reshape(3, 3)
b = np.array([0, 8, -9])
# 调用solve函数求解线性方程
C = np.linalg.solve(B, b)
C

array([29., 16.,  3.])

## 特征值和特征向量
* eigvals() &nbsp;只返回特征值
* eig() &nbsp; 返回特征值和特征向量

In [35]:
# A = np.array([3, -1, -1, 3]).reshape(2, 2)
# A = np.array([3, -2, 1, 0]).reshape(2, 2)
A = np.array([-1,1,0,-4,3,0,1,0,2]).reshape(3, 3)
A
eigenvalues_ = linalg.eigvals(A)
eigenvalues, eigenvectors = linalg.eig(A)
eigenvalues_
eigenvalues
eigenvalues = np.diag(eigenvalues) # 化对角阵
eigenvalues
eigenvectors # 列向量
"***"
# 验证，注意顺序
A@eigenvectors
eigenvectors@eigenvalues
# for i in eigenvalues_:
#     i*eigenvectors.T

array([[-1,  1,  0],
       [-4,  3,  0],
       [ 1,  0,  2]])

array([2., 1., 1.])

array([2., 1., 1.])

array([[2., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[ 0.  ,  0.41,  0.41],
       [ 0.  ,  0.82,  0.82],
       [ 1.  , -0.41, -0.41]])

'***'

array([[ 0.  ,  0.41,  0.41],
       [ 0.  ,  0.82,  0.82],
       [ 2.  , -0.41, -0.41]])

array([[ 0.  ,  0.41,  0.41],
       [ 0.  ,  0.82,  0.82],
       [ 2.  , -0.41, -0.41]])

## 奇异值分解

* 函数：np.linalg.svd(a,full_matrices=1,compute_uv=1)。  
* 参数：a是一个形如(M,N)矩阵full_matrices的取值是为0或者1，默认值为1，这时u的大小为(M,M)，v的大小为(N,N) 。否则u的大小为(M,K)，v的大小为(K,N) ，K=min(M,N)。compute_uv的取值是为0或者1，默认值为1，表示计算u,s,v。为0的时候只计算s。  
* 返回值：总共有三个返回值u,s,v  
    u大小为(M,M)，s大小为(M,N)，v大小为(N,N)。

<font color=blue>
关于奇异值的解释： <br> 
　　对于方阵而言$A=Q\sum Q^{-1}$  <br>
&emsp;&emsp;其中的$\sum$就是特征向量。但是对于不是方阵的矩阵而言就没有特征向量。 <br>  
&emsp;&emsp;非方阵的矩阵可以用奇异值分解来描述这个矩阵。A=$U\sum V^T$。其中U叫做左奇异值，$\sum$叫做奇异值，V叫做右奇异值。因为只有对角线的数不为0，并且数值是从大到小排列，所以一般只取r个，r的值越接近A的列数，那么三个矩阵的乘法得到的矩阵越接近A。   <br>
&emsp;&emsp;因为三个矩阵的面积之和远远小于原矩阵A，所以当我们向压缩空间表达A的时候，可以使用这三个矩阵。 <br>  
&emsp;&emsp;当A不是矩阵的时候，把A转置变为$A^T$。并且$A^T v=\lambda v$。其中的$v$就是右奇异值。$\partial = \sqrt{\lambda}$，这里的$\partial$就是上面的奇异值。$u=\frac{Av}{\partial}$，这里的u就是上面的左奇异值。 <br>
</font>

In [71]:
A = np.array([4, 11, 14, 8, 7, -2]).reshape(2,-1)
U,Sigma,V = np.linalg.svd(A,full_matrices=1)
A
U
Sigma = np.diag(Sigma)
Sigma
V
"***"

# U@Sigma
# U@Sigma@V
U[:,0]**2+U[:,1]**2
U[0,:]**2+U[1,:]**2
V[:,0]**2+V[:,1]**2+V[:,2]**2

# V[0,:]**2+V[1,:]**2+V[2,:]**2
# V[0,:]**2+V[1,:]**2
V@V.T

array([[ 4, 11, 14],
       [ 8,  7, -2]])

array([[-0.95, -0.32],
       [-0.32,  0.95]])

array([[18.97,  0.  ],
       [ 0.  ,  9.49]])

array([[-0.33, -0.67, -0.67],
       [ 0.67,  0.33, -0.67],
       [-0.67,  0.67, -0.33]])

'***'

array([1., 1.])

array([1., 1.])

array([1., 1., 1.])

array([[ 1., -0., -0.],
       [-0.,  1., -0.],
       [-0., -0.,  1.]])

In [72]:
data = np.mat([[1,2,3],[4,5,6]])
U,sigma,VT = np.linalg.svd(data)
U #[[-0.3863177  -0.92236578] [-0.92236578  0.3863177 ]]
sigma#[9.508032   0.77286964]
VT#[[-0.42866713 -0.56630692 -0.7039467 ] [ 0.80596391  0.11238241 -0.58119908] [ 0.40824829 -0.81649658  0.40824829]]


matrix([[-0.39, -0.92],
        [-0.92,  0.39]])

array([9.51, 0.77])

matrix([[-0.43, -0.57, -0.7 ],
        [ 0.81,  0.11, -0.58],
        [ 0.41, -0.82,  0.41]])

Help on function svd in module numpy.linalg:

svd(a, full_matrices=True, compute_uv=True)
    Singular Value Decomposition.
    
    When `a` is a 2D array, it is factorized as ``u @ np.diag(s) @ vh
    = (u * s) @ vh``, where `u` and `vh` are 2D unitary arrays and `s` is a 1D
    array of `a`'s singular values. When `a` is higher-dimensional, SVD is
    applied in stacked mode as explained below.
    
    Parameters
    ----------
    a : (..., M, N) array_like
        A real or complex array with ``a.ndim >= 2``.
    full_matrices : bool, optional
        If True (default), `u` and `vh` have the shapes ``(..., M, M)`` and
        ``(..., N, N)``, respectively.  Otherwise, the shapes are
        ``(..., M, K)`` and ``(..., K, N)``, respectively, where
        ``K = min(M, N)``.
    compute_uv : bool, optional
        Whether or not to compute `u` and `vh` in addition to `s`.  True
        by default.
    
    Returns
    -------
    u : { (..., M, M), (..., M, K) } array
        Unita

1.4193000000000002