In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = 'all'  #默认为'last'
%matplotlib inline

import numpy as np
import tensorflow

import matplotlib.pyplot as plt
import pandas as pd
import time
import os
import sys
import random
from numpy import linalg
np.set_printoptions(threshold=np.inf, precision=2, suppress=True)

In [3]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11493376/11490434 [==============================] - 299s 26us/step


In [5]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [6]:
model.fit(x_train, y_train, epochs=5)

model.evaluate(x_test,  y_test, verbose=2)

Train on 60000 samples
Epoch 1/5
60000/60000 [==============================] - 3s 58us/sample - loss: 0.2990 - accuracy: 0.9125
Epoch 2/5
60000/60000 [==============================] - 3s 51us/sample - loss: 0.1490 - accuracy: 0.9552
Epoch 3/5
60000/60000 [==============================] - 3s 51us/sample - loss: 0.1098 - accuracy: 0.9667
Epoch 4/5
60000/60000 [==============================] - 3s 51us/sample - loss: 0.0915 - accuracy: 0.9717
Epoch 5/5
60000/60000 [==============================] - 3s 52us/sample - loss: 0.0762 - accuracy: 0.9760


10000/10000 - 1s - loss: 0.0742 - accuracy: 0.9757


[0.07416248116875067, 0.9757]

In [11]:
a = tf.constant([1,2,3])
a
a.shape
a.dtype
a.numpy

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

TensorShape([3])

tf.int32

<bound method _EagerTensorBase.numpy of <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>>

In [15]:
tf.ones((4,3))

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [18]:
tf.random.normal(shape=(3,3),mean=0,stddev=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.61,  1.02,  0.12],
       [ 1.2 , -0.81, -0.36],
       [ 0.85,  1.25, -0.23]], dtype=float32)>

In [22]:
tf.random.uniform(shape=(3,3),minval=0,maxval=10)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[4.62, 2.68, 8.97],
       [7.3 , 6.13, 0.05],
       [1.63, 9.63, 1.77]], dtype=float32)>

In [30]:
tf.random.uniform(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.2 , 0.65, 0.31],
       [0.34, 0.97, 0.94],
       [0.72, 0.66, 0.65]], dtype=float32)>

In [43]:
# tf.random_normal([1,1,5,1])
tf.Variable([1,1,5,1])

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 1, 5, 1])>

In [31]:
help(tf.nn.conv2d)

Help on function conv2d_v2 in module tensorflow.python.ops.nn_ops:

conv2d_v2(input, filters, strides, padding, data_format='NHWC', dilations=None, name=None)
    Computes a 2-D convolution given 4-D `input` and `filters` tensors.
    
    Given an input tensor of shape `[batch, in_height, in_width, in_channels]`
    and a filter / kernel tensor of shape
    `[filter_height, filter_width, in_channels, out_channels]`, this op
    performs the following:
    
    1. Flattens the filter to a 2-D matrix with shape
       `[filter_height * filter_width * in_channels, output_channels]`.
    2. Extracts image patches from the input tensor to form a *virtual*
       tensor of shape `[batch, out_height, out_width,
       filter_height * filter_width * in_channels]`.
    3. For each patch, right-multiplies the filter matrix and the image patch
       vector.
    
    In detail, with the default NHWC format,
    
        output[b, i, j, k] =
            sum_{di, dj, q} input[b, strides[1] * i + d

In [72]:
input2 = tf.Variable(tf.constant(1.0, shape=[1, 5, 5, 1]))
filter2 = tf.Variable(tf.constant([-1.0, 0, 0, -1], shape=[2, 2, 1, 1]))
op2 = tf.nn.conv2d(input2, filter2, strides=[1, 2, 2, 1], padding='SAME')
input2
filter2
op2


<tf.Variable 'Variable:0' shape=(1, 5, 5, 1) dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

<tf.Variable 'Variable:0' shape=(2, 2, 1, 1) dtype=float32, numpy=
array([[[[-1.]],

        [[ 0.]]],


       [[[ 0.]],

        [[-1.]]]], dtype=float32)>

<tf.Tensor: shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[-2.],
         [-2.],
         [-1.]],

        [[-2.],
         [-2.],
         [-1.]],

        [[-1.],
         [-1.],
         [-1.]]]], dtype=float32)>

In [77]:
input1 = tf.Variable(tf.constant(1.0, shape=[1, 1, 5, 5]))
filter1 = tf.Variable(tf.constant(1.0, shape=[3, 3, 1, 1]))
# tf.nn.conv2d(input, filters, strides, padding, data_format='NHWC', dilations=None, name=None)
# tf.nn.conv2d(input=input1,filters=filter1,strides=1,padding="VALID")
tf.nn.conv2d(input=input1,filters=filter1,strides=[1,1,1,1],padding="SAME",data_format="NCHW")

<tf.Tensor: shape=(1, 1, 5, 5), dtype=float32, numpy=
array([[[[4., 6., 6., 6., 4.],
         [6., 9., 9., 9., 6.],
         [6., 9., 9., 9., 6.],
         [6., 9., 9., 9., 6.],
         [4., 6., 6., 6., 4.]]]], dtype=float32)>

In [63]:
input1

<tf.Tensor: shape=(1, 5, 5, 1), dtype=float32, numpy=
array([[[[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.]]]], dtype=float32)>

In [61]:
a = tf.constant([1,2,3,4],dtype=tf.float32)
tf.reshape(a,[2,2,1,-1])
tf.reshape(tf.constant([3,3,1,1],dtype=tf.float32),[2,2,1,-1])

<tf.Tensor: shape=(2, 2, 1, 1), dtype=float32, numpy=
array([[[[1.]],

        [[2.]]],


       [[[3.]],

        [[4.]]]], dtype=float32)>

<tf.Tensor: shape=(2, 2, 1, 1), dtype=float32, numpy=
array([[[[3.]],

        [[3.]]],


       [[[1.]],

        [[1.]]]], dtype=float32)>

In [57]:
filter1 = tf.constant([[[[1]],
  [[2]]],

 [[[ 3]],
  [[4]]]],dtype=tf.float32)
filter1

<tf.Tensor: shape=(2, 2, 1, 1), dtype=float32, numpy=
array([[[[1.]],

        [[2.]]],


       [[[3.]],

        [[4.]]]], dtype=float32)>

In [53]:
help(tf.reshape)

Help on function reshape in module tensorflow.python.ops.array_ops:

reshape(tensor, shape, name=None)
    Reshapes a tensor.
    
    Given `tensor`, this operation returns a new `tf.Tensor` that has the same
    values as `tensor` in the same order, except with a new shape given by
    `shape`.
    
    >>> t1 = [[1, 2, 3],
    ...       [4, 5, 6]]
    >>> print(tf.shape(t1).numpy())
    [2 3]
    >>> t2 = tf.reshape(t1, [6])
    >>> t2
    <tf.Tensor: shape=(6,), dtype=int32,
      numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>
    >>> tf.reshape(t2, [3, 2])
    <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
      array([[1, 2],
             [3, 4],
             [5, 6]], dtype=int32)>
    
    The `tf.reshape` does not change the order of or the total number of elements
    in the tensor, and so it can reuse the underlying data buffer. This makes it
    a fast operation independent of how big of a tensor it is operating on.
    
    >>> tf.reshape([1, 2, 3], [2, 2])
    Traceback (mos